In [6]:
python_list = [2,4,6,8,10]
python_list


[2, 4, 6, 8, 10]

In [12]:
import numpy as np
numpy_array1 = np.array(python_list)
numpy_array1

array([ 2,  4,  6,  8, 10])

In [1]:

def list_sum ():
    z = []
    for i in range (len(list_x)):
       list_total = (z.append (list_x [i] + list_y[i]))


list_x = list (range(100000))
list_y = list (range(100000))



SHAPE,SIZE and DATA TYPE OF AN ARRAY

In [31]:
import numpy as np
arr = np.array ([[5,6,7],[8,9,10],[11,12,13],[1,2,3]])
arr

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [ 1,  2,  3]])

In [35]:
arr.size

12

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr.shape

(4, 3)

In [38]:
arr.ndim

2

type() FUNCTION and dtype METHOD

In [39]:
type(arr)

numpy.ndarray

In [41]:
type (python_list)

list

In [42]:
python_list.dtype

AttributeError: 'list' object has no attribute 'dtype'

CREATING BASIC NUMPY ARRAYS

In [45]:
arr1 = np.arange(10) 
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr2 = np.zeros(7)
arr2

array([0., 0., 0., 0., 0., 0., 0.])

In [50]:
arr3 = np.ones(4)
arr3

array([1., 1., 1., 1.])

In [5]:
import numpy as np
arr4 = np.linspace(start=1, stop=10)
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [11]:
arr5 = np.linspace(1, 10, num=12, endpoint=False)
arr5

array([1.  , 1.75, 2.5 , 3.25, 4.  , 4.75, 5.5 , 6.25, 7.  , 7.75, 8.5 ,
       9.25])

ADD, REMOVE and SORT
1. Adding an Element
    i. Create a NumPy array:
        arr = np.array
        arr
        array ([2,5,7,3,4,6])
    ii. You can use append method to add an element in a NumPy array:
        np.append(arr,15)
        array([2,5,7,3,4,6,15])
    iii. You can also add an element to a python list using the np.append() method. But the returned object is a NumPy array
        l = [2,5,7,3,4,6,15]
        arr = np.append(l, 10)
        arr
        array([2,5,4,6,7,10])
        type(arr)
        numpy.ndarray
    iv. You can also add a list of elemnts. Try doing this by yourself. For example,
        np.append (arr,[11,22])
2. Removing Elements
    1. You can remove element from an array using the delete method of NumPy
        arr = np.array ([2,,5,7,3,4,6])
        arr
        array ([2,,5,7,3,4,6])
    ii. You can also remove an element from a python list using np.delete() method
        import numpy as np
        python_list = [2,,5,7,3,4,6]
        np.delete(python_list,1)
3. Sorting and Array
    i. You can quickly sort an array in ascending order as:
        arr
        array([2,5,7,3,4,6])
        np.sort(arr)
        array([2,3,4,5,6,7])

In [15]:
import numpy as np
arr6 = np.array([2,5,7,3,4,6])
arr6
np.append(arr6, 8)

array([2, 5, 7, 3, 4, 6, 8])

In [17]:
np.append(arr6, [28,9,13])

array([ 2,  5,  7,  3,  4,  6, 28,  9, 13])

In [18]:
np.sort(arr6)

array([2, 3, 4, 5, 6, 7])

In [19]:
np.delete (arr6, 2)

array([2, 5, 3, 4, 6])

RESHAPING

In [24]:
L = [x for x in range (1,10,1)]
L
np.array(L)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
L = np.arange(1,10,1)
reshaped_arr = np.reshape(L,(3,3))
reshaped_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
reshaped_arr = np.arange(9).reshape((3,3))
reshaped_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr7 = np.arange(24)
arrayT = np.reshape(arr7,(2,12))
arrayT

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

INDEXING AND SLICING
1.  Positive Indexing
2.  Negative Indexing

In [52]:
arrayT[1][7]

19

In [53]:
arrayT[0:2,0:3]

array([[ 0,  1,  2],
       [12, 13, 14]])

In [14]:
from PIL import Image
from numpy import asarray

img = Image.open ('A.jpeg')
numpydata = asarray(img)
numpydata

array([[[ 40,  34,  22],
        [ 40,  34,  22],
        [ 41,  35,  23],
        ...,
        [ 99,  69,  33],
        [102,  72,  36],
        [103,  73,  37]],

       [[ 41,  35,  23],
        [ 40,  34,  22],
        [ 40,  34,  22],
        ...,
        [104,  74,  38],
        [105,  75,  41],
        [107,  77,  41]],

       [[ 41,  35,  23],
        [ 41,  35,  23],
        [ 40,  34,  22],
        ...,
        [106,  76,  42],
        [108,  77,  46],
        [109,  79,  45]],

       ...,

       [[102,  96,  64],
        [102,  96,  64],
        [102,  96,  64],
        ...,
        [150, 144, 132],
        [150, 144, 132],
        [150, 144, 132]],

       [[102,  96,  64],
        [102,  96,  64],
        [102,  96,  64],
        ...,
        [150, 144, 132],
        [150, 144, 132],
        [150, 144, 132]],

       [[102,  96,  64],
        [102,  96,  64],
        [103,  97,  65],
        ...,
        [150, 144, 132],
        [150, 144, 132],
        [150, 144, 132]]

In [4]:
pilImage = Image.fromarray(numpydata)
pilImage.save ('W.jpeg')
pilImage.show()
print(pilImage)
print(type(pilImage))
print(pilImage.mode)
print(pilImage.size)

NameError: name 'numpydata' is not defined

In [2]:
from PIL import Image
import numpy as np
original = np.random.random((28,28,3),dtype=uint8)
print (original)
img = Image.fromarray(original)
img.show()



NameError: name 'uint8' is not defined

In [1]:
from PIL import Image
import numpy as np
arr = np.random.randint(255, size=(28, 28),dtype=np.uint8)
print(arr)
img = Image.fromarray(arr)
img.show()

[[ 98  59 178  96 160  40  41 190  79  65  47 108 147 164 144 158  55 142
   40 250 105 211 193 107  23  66   8 173]
 [251 184  36 142 201  26  34  38  57 209 248 203 104 118 230 233 220 209
  187  34  48  84 176 114 193 182   3  69]
 [108 172  16  60  57 199 144 156  96  28 162  34   2  47  71 246 195 246
  225  39  56 136  33 101 186 116 190 181]
 [ 58  28 138 115 142 126  96 187 221 253 155 209  95  63 140 100 117 211
  221 154 190  35 165   8 209  58 224 209]
 [109 147  13  78 158   2 170 233  50 201 112  89 199 231 207  77 134 191
  161 181 177  64  64  21 210 168 143  23]
 [221  90  51 167 113  85 139 133  11 225 199  93 243  70 236 175 133 107
   17 185 119   2  36 223 135 148 193 184]
 [156 253  48 218 184  55 253  87 191 139  43  78  21 130 218  73  65 169
   88  95  90 142 254 175  69  15 251 110]
 [237 179  37 245 163  96 124 113 223 198  42 159 101 176 103  47  46 147
  175 127 151  39 217  94  97 137 192  22]
 [ 40  52 249  44 225 126 238 118  22  75 205 103 121  23  60  4

In [20]:
arr = np.random.randint(0,256, size=(3,28, 28),dtype=np.uint8)
print(arr)
print(arr[1,1,:10])

[[[152 190  30 ...  83 234 197]
  [228 158   8 ... 182  79 105]
  [134  77  84 ... 190 242  30]
  ...
  [ 45 245 148 ... 138  17  53]
  [137 236 232 ... 154  18  76]
  [138   9 252 ...  63  49 232]]

 [[142 124 189 ...  51  50 205]
  [218  23 119 ...  76  87   6]
  [119  28 211 ... 158  59   8]
  ...
  [  1 166  67 ... 219  31 227]
  [153 137 195 ... 216 205 251]
  [161 178  61 ... 245  36 154]]

 [[ 28 236 222 ...  31 125  26]
  [159  69 113 ... 172   2  21]
  [164  21   4 ... 250 164 169]
  ...
  [ 38 255  63 ... 152 153  37]
  [ 99  59 186 ... 114  95 132]
  [ 97 150  91 ... 252   7 147]]]
[218  23 119 123  26  52  55  46 217  95]
